run:
  deadline: 5m
  tests: false
  silent: true

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  lll:
    line-length: 180

linters:
  enable-all: true
  disable:
    - funlen
    - gas
    - gochecknoglobals
    - interfacer
    - maligned
    - nakedret
    - stylecheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - composite literal uses unkeyed fields
    - Error return value of `.+\.Close` is not checked
    - method Json should be JSON
