run:
  deadline: 5m
  tests: true
  allow-parallel-runners: true
  modules-download-mode: readonly
  build-tags: [ all, integration ]

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
  goimports:
    local-prefixes: github.com/scylladb/gocqlx
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - shadow
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - evalOrder
      - hugeParam
      - importShadow
      - yodaStyleExpr
      - whyNoLint
  lll:
    line-length: 180

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gofumpt
    - goheader
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unused
    - forbidigo

issues:
  new: true
  new-from-rev: origin/master
  exclude-use-default: false
  exclude:
    - composite literal uses unkeyed fields
    - Error return value of `.+\.Close` is not checked
    - method Json should be JSON
  exclude-rules:
    - path: (.*_test.go|migrate/example|gocqlxtest/)
      linters:
        - fieldalignment
        - govet
        - errcheck
    - path: doc_test.go
      linters:
        - unused
        - revive

