name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # On CICD following error shows up:
  #   go: github.com/gocql/gocql@v1.7.0: GOPROXY list is not the empty string, but contains no entries
  # This env variable is set to make it go away
  # If at some point you see no error, feel free to remove it
  GOPROXY: direct
  # On CICD following error shows up:
  #   go: golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.24.0: golang.org/x/tools@v0.24.0: verifying module: missing GOSUMDB
  # This env variable makes it go away
  # If at some point you see no error, feel free to remove it
  GOSUMDB: off

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: '0'

      - name: Install Go 1.25
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.25

      - name: Cache Dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        id: gomod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'cmd/schemagen/testdata/go.mod') }}

      - name: Download Dependencies
        run: git --version && make get-deps && make get-tools

      - name: Lint
        run: make check
          
      - name: Test
        run: make test
