name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # On CICD following error shows up:
  #   go: github.com/gocql/gocql@v1.7.0: GOPROXY list is not the empty string, but contains no entries
  # This env variable is set to make it go away
  # If at some point you see no error, feel free to remove it
  GOPROXY: direct
  # On CICD following error shows up:
  #   go: golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.24.0: golang.org/x/tools@v0.24.0: verifying module: missing GOSUMDB
  # This env variable makes it go away
  # If at some point you see no error, feel free to remove it
  GOSUMDB: off

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: '0'

      - name: Install Go 1.25
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.25

      - name: Cache Dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: gomod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'cmd/schemagen/testdata/go.mod') }}

      - name: Download Dependencies
        run: git --version && make get-deps && make get-tools

      - name: Lint
        run: make check
          
      - name: Test
        run: make test
